### ISSUE TITLE
reshuffle train cards threw a server error

### ISSUE THREAD

**Issue by jtcooper** [cs340tabyu/cs340summer2018#25]
I drew my second train card for my turn, the replacement in the face-up cards was a locomotive, since there were already two locomotives, it discarded all of them and tried to replace all the cards. Since there were 5 or fewer cards left in the train card deck (I don't remember if it was less than 5), it triggered a reshuffle. I got a bunch of messages saying everything was reshuffling, etc. and then got a toast that said “method failed” and then “internal server error” and then there were no cards in the face up card or train card deck. Someone else’s client crashed after he tried to view his hand.

I think it's just the reshuffle method failing. We reproduced the bug a second time and got the same message, "Shuffle not possible. Method failed!"

Server:
java.lang.StringIndexOutOfBoundsException: start -2, end -1, length 0
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1698)
	at java.base/java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:837)
	at java.base/java.lang.StringBuilder.delete(StringBuilder.java:251)
	at edu.cs340.spring2018group3.common.model.destinationcard.DcIdList.toString(DcIdList.java:28)
	at edu.cs340.spring2018group3.server.junction.CommandManager.makeMarkDcsCompletedCommands(CommandManager.java:331)
	at edu.cs340.spring2018group3.server.junction.ServerFacade.confirmDcDraw(ServerFacade.java:276)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at edu.cs340.spring2018group3.common.command.Command.execute(Command.java:49)
	at edu.cs340.spring2018group3.server.Handler.handle(Handler.java:25)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:691)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:663)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:444)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:409)
	at java.base/java.lang.Thread.run(Thread.java:844)
**java.lang.Exception: Shuffle not possible. Method Failed!**
	at edu.cs340.spring2018group3.server.service.TcService.shuffleTcDeck(TcService.java:68)
	at edu.cs340.spring2018group3.server.junction.ServerFacade.shuffleTcDeck(ServerFacade.java:334)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at edu.cs340.spring2018group3.common.command.Command.execute(Command.java:49)
	at edu.cs340.spring2018group3.server.Handler.handle(Handler.java:25)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:691)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:663)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:444)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:409)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by tylermercer** [comment]
Thanks for such a detailed bug report!
