### ISSUE TITLE
Shows toast (Show -2, length -1, points 0) after claiming route

### ISSUE THREAD

**Issue by jtcooper** [cs340tabyu/cs340summer2018#49]
Only happens sometimes, not every time.

**Comment by dvwilliamson** [comment]
Example Log
______________________________________
Entered ServerFacade.drawThreeDcs for paul
Entered ServerFacade.confirmDcDraw for paul
cheese: Returning Vancouver to SantaFe, 13 pts to deck!
cheese: Returning Denver to Pittsburgh, 11 pts to deck!
makeSetTurnCommands
java.lang.StringIndexOutOfBoundsException: start -2, end -1, length 0
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1698)
	at java.base/java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:837)
	at java.base/java.lang.StringBuilder.delete(StringBuilder.java:251)
	at edu.cs340.spring2018group3.common.model.destinationcard.DcIdList.toString(DcIdList.java:28)
	at edu.cs340.spring2018group3.server.junction.CommandManager.makeMarkDcsCompletedCommands(CommandManager.java:331)
	at edu.cs340.spring2018group3.server.junction.ServerFacade.confirmDcDraw(ServerFacade.java:276)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at edu.cs340.spring2018group3.common.command.Command.execute(Command.java:49)
	at edu.cs340.spring2018group3.server.Handler.handle(Handler.java:25)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:691)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:663)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:444)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:409)
	at java.base/java.lang.Thread.run(Thread.java:844)
Entered ServerFacade.confirmTcDraw for dallas
makeSetTurnCommands
Entered ServerFacade.chat for josh
Entered ServerFacade.claimRoute for josh
makeSetTurnCommands
java.lang.StringIndexOutOfBoundsException: start -2, end -1, length 0
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1698)
	at java.base/java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:837)
	at java.base/java.lang.StringBuilder.delete(StringBuilder.java:251)
	at edu.cs340.spring2018group3.common.model.destinationcard.DcIdList.toString(DcIdList.java:28)
	at edu.cs340.spring2018group3.server.junction.CommandManager.makeMarkDcsCompletedCommands(CommandManager.java:331)
	at edu.cs340.spring2018group3.server.junction.ServerFacade.claimRoute(ServerFacade.java:482)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at edu.cs340.spring2018group3.common.command.Command.execute(Command.java:49)
	at edu.cs340.spring2018group3.server.Handler.handle(Handler.java:25)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:691)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:663)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:444)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:409)
	at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by tylermercer** [comment]
(this is just for my team's reference)

This is a problem with DcIdList.toString() when the DcIdList is empty
